# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0

DEFAULT_STATISTICS: str
DEFAULT_PINNED_MEMORY: bool
DEFAULT_PINNED_INITIAL_POOL_SIZE: str
DEFAULT_PINNED_MAX_POOL_SIZE: str
DEFAULT_SPILL_DEVICE_LIMIT: str
DEFAULT_PERIODIC_SPILL_CHECK: str
DEFAULT_NUM_STREAMS: int
DEFAULT_NUM_STREAMING_THREADS: int
DEFAULT_MEMORY_RESERVE_TIMEOUT: str
DEFAULT_LOG: str
DEFAULT_UCXX_PROGRESS_MODE: str
