# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from collections.abc import Mapping
from enum import IntEnum

from rapidsmpf.communicator.communicator import Communicator
from rapidsmpf.memory.buffer_resource import BufferResource
from rapidsmpf.memory.packed_data import PackedData

class PartitionAssignment(IntEnum):
    ROUND_ROBIN = ...
    CONTIGUOUS = ...

class Shuffler:
    max_concurrent_shuffles: int
    def __init__(
        self,
        comm: Communicator,
        op_id: int,
        total_num_partitions: int,
        br: BufferResource,
        partition_assignment: PartitionAssignment = ...,
    ) -> None: ...
    def shutdown(self) -> None: ...
    def __str__(self) -> str: ...
    @property
    def comm(self) -> Communicator: ...
    def insert_chunks(self, chunks: Mapping[int, PackedData]) -> None: ...
    def insert_finished(self) -> None: ...
    def extract(self, pid: int) -> list[PackedData]: ...
    def finished(self) -> bool: ...
    def wait(self) -> None: ...
    def local_partitions(self) -> list[int]: ...
