# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from enum import IntEnum
from os import PathLike
from typing import Any, Self

from rapidsmpf.config import Options
from rapidsmpf.memory.pinned_memory_resource import PinnedMemoryResource
from rapidsmpf.memory.scoped_memory_record import ScopedMemoryRecord
from rapidsmpf.rmm_resource_adaptor import RmmResourceAdaptor

class Formatter(IntEnum):
    Default = ...
    Bytes = ...
    Duration = ...
    HitRate = ...
    MemoryThroughput = ...

class Statistics:
    def __init__(self, *, enable: bool) -> None: ...
    @classmethod
    def from_options(cls: type[Self], options: Options) -> Self: ...
    @property
    def enabled(self) -> bool: ...
    def report(
        self,
        *,
        mr: RmmResourceAdaptor | None = None,
        pinned_mr: PinnedMemoryResource | None = None,
        header: str | None = None,
    ) -> str: ...
    def get_stat(self, name: str) -> dict[str, int | float]: ...
    def list_stat_names(self) -> list[str]: ...
    def to_dict(self) -> dict[str, dict[str, int | float]]: ...
    def add_stat(self, name: str, value: float) -> None: ...
    def add_report_entry(
        self,
        name: str,
        stat_names: Iterable[str],
        formatter: Formatter,
    ) -> None: ...
    def get_memory_records(self) -> dict[str, MemoryRecord]: ...
    def memory_profiling(
        self, mr: RmmResourceAdaptor | None, name: str
    ) -> MemoryRecorder: ...
    def copy(self) -> Statistics: ...
    @staticmethod
    def merge(stats: Sequence[Statistics]) -> Statistics: ...
    def clear(self) -> None: ...
    def write_json(self, filepath: str | PathLike[str]) -> None: ...
    def write_json_string(self) -> str: ...
    def serialize(self) -> bytes: ...
    @staticmethod
    def deserialize(buf: bytes) -> Statistics: ...

@dataclass
class MemoryRecord:
    scoped: ScopedMemoryRecord
    global_peak: int
    num_calls: int

class MemoryRecorder:
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: Any | None,
    ) -> bool: ...
