# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from enum import IntEnum

class MemoryType(IntEnum):
    DEVICE = ...
    PINNED_HOST = ...
    HOST = ...

class Buffer:
    @property
    def size(self) -> int: ...
    @property
    def mem_type(self) -> MemoryType: ...
    def __buffer__(self, flags: int, /) -> memoryview: ...
