# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from contextlib import AbstractContextManager
from enum import IntEnum

class MemoryType(IntEnum):
    DEVICE = ...
    PINNED_HOST = ...
    HOST = ...

class BufferHostView(AbstractContextManager[memoryview]):
    def __enter__(self) -> memoryview: ...
    def __exit__(self, *args: object) -> None: ...

class Buffer:
    @property
    def size(self) -> int: ...
    @property
    def mem_type(self) -> MemoryType: ...
    def host_view(self) -> BufferHostView: ...
