# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0

class ScopedMemoryRecord:
    def num_total_allocs(self) -> int: ...
    def num_current_allocs(self) -> int: ...
    def current(self) -> int: ...
    def total(self) -> int: ...
    def peak(self) -> int: ...
    def record_allocation(self, nbytes: int) -> None: ...
    def record_deallocation(self, nbytes: int) -> None: ...
