# SPDX-FileCopyrightText: Copyright (c) 2024-2025, NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0

{% set version = environ['RAPIDS_PACKAGE_VERSION'].lstrip('v') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: librapidsmp-split

source:
  git_url: ../../..

build:
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - PARALLEL_LEVEL
    - RAPIDS_ARTIFACTS_DIR
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=librapidsmp-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=librapidsmp-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL
    - SCCACHE_S3_NO_CREDENTIALS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cuda-version ={{ cuda_version }}
    - cmake {{ cmake_version }}
    - ninja
    - {{ stdlib("c") }}
  host:
    - cuda-version ={{ cuda_version }}
    - cuda-cudart-dev
    - librmm ={{ minor_version }}
    - libcudf ={{ minor_version }}
    - openmpi  # See <https://github.com/rapidsai/rapids-multi-gpu/issues/17>
    - ucxx {{ ucxx_version }}

outputs:
  - name: librapidsmp
    version: {{ version }}
    script: install_librapidsmp.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      run_exports:
        - {{ pin_subpackage("librapidsmp", max_pin="x.x") }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
        - cuda-cudart-dev
    requirements:
      build:
        - cmake {{ cmake_version }}
      host:
        - cuda-version ={{ cuda_version }}
        - cuda-cudart-dev
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        - cuda-cudart
        - librmm ={{ minor_version }}
        - libcudf ={{ minor_version }}
        - openmpi  # See <https://github.com/rapidsai/rapids-multi-gpu/issues/17>
        - ucxx {{ ucxx_version }}
    test:
        commands:
          - test -f $PREFIX/include/rapidsmpf/communicator/communicator.hpp
    about:
      home: https://rapids.ai
      license: Apache-2.0
      license_family: Apache
      license_file: LICENSE
      summary: librapidsmp library
  - name: librapidsmp-tests
    version: {{ version }}
    script: install_librapidsmp_tests.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
        - cuda-cudart-dev
    requirements:
      build:
        - cmake {{ cmake_version }}
      host:
        - cuda-version ={{ cuda_version }}
        - cuda-cudart-dev
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        - cuda-cudart
        - librmm ={{ minor_version }}
        - libcudf ={{ minor_version }}
        - openmpi  # See <https://github.com/rapidsai/rapids-multi-gpu/issues/17>
        - ucxx {{ ucxx_version }}
    about:
      home: https://rapids.ai
      license: Apache-2.0
      license_family: Apache
      license_file: LICENSE
      summary: librapidsmp tests
