# Copyright (c) 2025, NVIDIA CORPORATION.

class Logger:
    def warn(self, msg: str) -> None: ...
    def info(self, msg: str) -> None: ...
    def debug(self, msg: str) -> None: ...
    def trace(self, msg: str) -> None: ...

class Communicator:
    @property
    def rank(self) -> int: ...
    @property
    def nranks(self) -> int: ...
    @property
    def logger(self) -> Logger: ...
