# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_abi_min: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring : ${{ py_abi_min | version_to_buildstring }}
  py_runtime_latest: "3.13"
  head_rev: ${{ git.head_rev(".")[:8] }}
  ucxx_version: ${{ env.get("UCXX_PACKAGE_DEPENDENCY") }}

package:
  name: rapidsmpf
  version: ${{ version }}

source:
  path: ../../..

build:
  python:
    version_independent: true
  string: cuda${{ cuda_major }}_cp${{ py_buildstring }}_abi3_${{ date_string }}_${{ head_rev }}
  files:
    exclude:
      # libarrow feedstock incorrectly ships this file so we exclude it manually
      - '*libarrow.so.*gdb.py'
  dynamic_linking:
    overlinking_behavior: "error"
    missing_dso_allowlist:
      - lib/libpython*.so.*
  prefix_detection:
    # See https://github.com/rapidsai/build-planning/issues/160
    # Blanket ignore here as there are quite a few shared objects shipped in rapidsmpf
    ignore_binary_files: True
  script:
    content: |
      ./build.sh -v rapidsmpf
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - SCCACHE_DIST_AUTH_TOKEN
    env:
      CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
      CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
      CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
      CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
      NVCC_APPEND_FLAGS: ${{ env.get("NVCC_APPEND_FLAGS", default="") }}
      PARALLEL_LEVEL: ${{ env.get("PARALLEL_LEVEL", default="8") }}
      RAPIDS_ARTIFACTS_DIR: ${{ env.get("RAPIDS_ARTIFACTS_DIR", default="") }}
      RAPIDS_PY_VERSION: ${{ py_abi_min }}
      SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET", default="") }}
      SCCACHE_DIST_AUTH_TYPE: ${{ env.get("SCCACHE_DIST_AUTH_TYPE", default="token") }}
      SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE: ${{ env.get("SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE", default="false") }}
      SCCACHE_DIST_MAX_RETRIES: ${{ env.get("SCCACHE_DIST_MAX_RETRIES", default="inf") }}
      SCCACHE_DIST_REQUEST_TIMEOUT: ${{ env.get("SCCACHE_DIST_REQUEST_TIMEOUT", default="7140") }}
      SCCACHE_DIST_SCHEDULER_URL: ${{ env.get("SCCACHE_DIST_SCHEDULER_URL", default="") }}
      SCCACHE_ERROR_LOG: ${{ env.get("SCCACHE_ERROR_LOG", default="/tmp/sccache.log") }}
      SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT", default="0") }}
      SCCACHE_NO_CACHE: ${{ env.get("SCCACHE_NO_CACHE", default="") }}
      SCCACHE_RECACHE: ${{ env.get("SCCACHE_RECACHE", default="") }}
      SCCACHE_REGION: ${{ env.get("SCCACHE_REGION", default="") }}
      SCCACHE_S3_KEY_PREFIX: rapidsmpf/${{ env.get("RAPIDS_CONDA_ARCH") }}/cuda${{ cuda_major }}
      SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS", default="false") }}
      SCCACHE_S3_PREPROCESSOR_CACHE_KEY_PREFIX: rapidsmpf/${{ env.get("RAPIDS_CONDA_ARCH") }}/cuda${{ cuda_major }}/conda/preprocessor-cache
      SCCACHE_S3_USE_PREPROCESSOR_CACHE_MODE: ${{ env.get("SCCACHE_S3_USE_PREPROCESSOR_CACHE_MODE", default="true") }}
      SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL", default="true") }}
      SCCACHE_SERVER_LOG: ${{ env.get("SCCACHE_SERVER_LOG", default="sccache=debug") }}

requirements:
  build:
    - cmake ${{ cmake_version }}
    - ninja
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("cuda") }}
    - cuda-cupti-dev
    - cuda-version =${{ cuda_version }}
    - libnuma
    - ${{ stdlib("c") }}
  host:
    - cuda-cudart-dev
    - cuda-cupti-dev
    - cuda-version =${{ cuda_version }}
    - cython >=3.2.2
    - librapidsmpf =${{ version }}
    - libnuma
    - mpi4py
    - openmpi >=5.0
    - pip
    - pylibcudf =${{ minor_version }}
    - python =${{ py_abi_min }}
    - python-abi3 ${{ py_abi_min }}.*
    - rapids-build-backend >=0.4.0,<0.5.0
    - rmm =${{ minor_version }}
    - scikit-build-core>=0.11.0
    - ucxx ${{ ucxx_version }}
  run:
    - cuda-cupti
    - if: cuda_major == "12"
      then: cuda-python >=12.9.2,<13.0
      else: cuda-python >=13.0.1,<14.0
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
    - cudf =${{ minor_version }}
    - cupy >=13.6.0
    - librapidsmpf =${{ version }}
    - mpi4py
    - numpy >=1.23,<3.0
    - openmpi >=5.0
    - pylibcudf =${{ minor_version }}
    - python
    - rmm =${{ minor_version }}
    - ucxx ${{ ucxx_version }}
  run_constraints:
    - dask-cuda =${{ minor_version }}
    - dask-cudf =${{ minor_version }}
  ignore_run_exports:
    from_package:
      - ${{ compiler("c") }}
      - ${{ compiler("cxx") }}
      - ${{ compiler("cuda") }}
      - ${{ stdlib("c") }}
    by_name:
      - cuda-cudart
      - cuda-cupti
      - cuda-version
      - openmpi
      - mpi4py
      - python_abi

tests:
  - python:
      imports:
        - rapidsmpf
      python_version: ${{ py_runtime_latest }}.*
      pip_check: false

about:
  homepage: ${{ load_from_file("python/rapidsmpf/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/rapidsmpf/pyproject.toml").project.license }}
  summary: ${{ load_from_file("python/rapidsmpf/pyproject.toml").project.description }}
