# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0

def get_total_host_memory() -> int: ...
def get_current_numa_node() -> int: ...
def get_numa_node_host_memory(numa_id: int | None = None) -> int: ...
