# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0
"""Type stubs for channel_metadata module."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Literal, Self

import pylibcudf as plc

from rapidsmpf.streaming.core.message import Message
from rapidsmpf.streaming.cudf.table_chunk import TableChunk

class HashScheme:
    def __init__(self, column_indices: Sequence[int], modulus: int) -> None: ...
    @property
    def column_indices(self) -> tuple[int, ...]: ...
    @property
    def modulus(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class OrderScheme:
    def __init__(
        self,
        column_indices: Sequence[int],
        orders: Sequence[plc.types.Order],
        null_orders: Sequence[plc.types.NullOrder],
        boundaries: TableChunk | None = None,
        *,
        strict_boundary: bool = False,
    ) -> None: ...
    @property
    def column_indices(self) -> tuple[int, ...]: ...
    @property
    def orders(self) -> tuple[plc.types.Order, ...]: ...
    @property
    def null_orders(self) -> tuple[plc.types.NullOrder, ...]: ...
    @property
    def has_boundaries(self) -> bool: ...
    @property
    def strict_boundary(self) -> bool: ...
    def get_boundaries_table(self) -> plc.Table | None: ...
    # Shallow equality: boundary values not compared.
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

PartitioningSpecValue = HashScheme | OrderScheme | None | Literal["inherit"]

class Partitioning:
    def __init__(
        self,
        inter_rank: PartitioningSpecValue = None,
        local: PartitioningSpecValue = None,
    ) -> None: ...
    @property
    def inter_rank(self) -> PartitioningSpecValue: ...
    @property
    def local(self) -> PartitioningSpecValue: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class ChannelMetadata:
    def __init__(
        self,
        local_count: int,
        *,
        partitioning: Partitioning | None = None,
        duplicated: bool = False,
    ) -> None: ...
    @classmethod
    def from_message(cls: type[Self], message: Message[Self]) -> ChannelMetadata: ...
    def into_message(self, sequence_number: int, message: Message[Self]) -> None: ...
    @property
    def local_count(self) -> int: ...
    @property
    def partitioning(self) -> Partitioning: ...
    @property
    def duplicated(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
